config/routes.rb
Rails.application.routes.draw do
  # get 'contacts/new'
  # get 'contacts/create'
  get 'home/about'
  #get 'staffs/create'
  #get 'staffs/destroy'
  #get 'relationships/create'
  #get 'relationships/destroy'
  #get 'users/show'
  #get 'clothes/index'
  #get 'posts/index'
  #get 'posts/show'
  #get 'posts/new'
  #get 'posts/create'
  #get 'posts/edit'
  #get 'posts/search'

  root "posts#index"

  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  
  # /shop/newを習得
  devise_scope :user do
    get '/shop/new' => 'users/registrations#shop', as: :new_shop
    get '/shop/edit' => 'users/registrations#shop_edit', as: :edit_shop
  end

  resources :users, only: [:show] do
    collection do
      get :setting
    end
    resource :relationships, only: [:create, :destroy]
    resource :staffs, only: [:create, :destroy]
  end

  resources :posts do
  	collection do
  		get :search
  	end
    member do
      get :new2
    end
    resources :clothes, only: [:create, :destroy]
    resources :likes, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
  end
  
  resources :contacts, only: [:new, :create]

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  	devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable#, :confirmable

    # ビュー数
    is_impressionable

    has_many :posts, dependent: :destroy
    has_many :likes, dependent: :destroy
    # userがどの投稿をいいねしているのか
  	has_many :liked_posts, through: :likes, source: :post
  	
    has_many :active_relationships, class_name: "Relationship", foreign_key: :following_id
    has_many :followings, through: :active_relationships, source: :follower
    has_many :passive_relationships, class_name: "Relationship", foreign_key: :follower_id
    has_many :followers, through: :passive_relationships, source: :following

    has_many :active_staffs, class_name: "Staff", foreign_key: :registering_id
    has_many :registerings, through: :active_staffs, source: :registered
    has_many :passive_staffs, class_name: "Staff", foreign_key: :registered_id
    has_many :registereds, through: :passive_staffs, source: :registering

  	has_many :comments, dependent: :destroy
  	belongs_to :area, optional: true

    has_one :shop, inverse_of: :user, dependent: :destroy
    #shopのフォームでuserを保存
    accepts_nested_attributes_for :shop, allow_destroy: true
    

    mount_uploader :photo, PhotoUploader



    # follow済み？
    def followed_by?(user)
       passive_relationships.find_by(following_id: user.id).present?
    end

    # staff登録済み？
    def staffed_by?(user)
       passive_staffs.find_by(registering_id: user.id).present?
    end

    #  like済み？
    def already_liked?(post)
      self.likes.exists?(post_id: post.id)
    end

end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end


  # shopの登録フォーム
  def shop
    @user = User.new
    @user.build_shop
  end

  def shop_edit
    @user = current_user
    @user.shop.id
  end

  # POST /resource
  def create
    super
    # resource.update(confirmed_at: Time .now.utc)# Welcomeメールを送信した上で、skip_confirmation!と同一処理を行い自動で認証クローズさせる
    @user = User.new(configure_sign_up_params)
    @user.save
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  def update
    super
    @user = User.new(configure_account_update_params)
    @user.save
  end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [
      :name, :age, :photo, :height, :gender, :facebook_url,
      :twitta_url, :instaguram_url, :shop_id, :area_id,
      shop_attributes: [:phone, :hp_url, :user_id]])
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [
      :name, :age, :photo, :height, :gender, :facebook_url,
      :twitta_url, :instaguram_url, :shop_id, :area_id,
      shop_attributes: [:phone, :hp_url, :user_id]])
  end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: [:setting]
  def show
  	@user = User.find(params[:id])
  	@posts = @user.posts.all.page(params[:user_post_page]).per(15)
    @likes = @user.liked_posts.all.page(params[:like_post_page]).per(15)
  	@followers = @user.followers
    @followings = @user.followings
  	@staffs = @user.registerings
    
  	
  end


  def setting
    @user = User.find_by(id: current_user.id)
    @posts = @user.posts.all
    @followings = @user.followings
    @followers = @user.followers
    @staffs = @user.registerings
    
  
  end

end

app/helpers/users_helper.rb
module UsersHelper
  def bootstrap_devise_error_messages!
    return "" if resource.errors.empty?

    html = ""
    resource.errors.full_messages.each do |error_message|
      html += <<-EOF
      <div class="alert alert-danger alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert">
          <span aria-hidden="true">&times;</span>
          <span class="sr-only">close</span>
        </button>
        #{error_message}
      </div>
      EOF
    end
    html.html_safe
  end
end

app/views/users/_user.info.html.erb
<div class="container bg-white p-3">
  <div class="row">
    <% unless @user.shop.blank? %>
      <div class="col-11 pb-4 user-img-center">
        <%= link_to image_tag(@user.photo_url, class: "img-fluid rounded-circle icon-trim-user-show d-block mx-auto"), user_path(@user) %>
      </div>
      <div class="col-12">
        <h4 class="mb-2 text-dark">
          名前 : <%= @user.name %>
        </h4>
        <h4 class="mb-2 text-dark">
          地域 : 
          <% unless @user.area.blank? %>
           <%= @user.area.prefecture %>
          <% end %>
        </h4>
        <h4 class="mb-2 text-dark">
          tell : 
          <% unless @user.shop.phone.blank? %>
           <%= @user.shop.phone %>
          <% end %>
        </h4>
        <h4 class="mb-2 text-dark">
          HP : 
          <% unless @user.shop.hp_url.blank? %>
           <%= link_to @user.shop.hp_url do %><%= @user.shop.hp_url %><% end %>
          <% end %>
        </h4>
        <h4 class="mb-2 text-dark">
          fecebook : 
          <% unless @user.facebook_url.blank? %>
            <%= link_to @user.facebook_url, class: "text-primary" do %><i class="fab fa-facebook-square"></i> <-click<% end %>
          <% end %>
        </h4>
        <h4 class="mb-2 text-dark">
          twitta : 
          <% unless @user.twitta_url.blank? %>
            <%= link_to @user.twitta_url, class: "text-info" do %><i class="fab fa-twitter-square"></i> <-click<% end %>
          <% end %>
        </h4>
        <h4 class="mb-2 text-dark">
          instaguram : 
          <% unless @user.instaguram_url.blank? %>
            <%= link_to @user.instaguram_url, class: "text-warning" do %><i class="fab fa-instagram"></i> <-click<% end %>
          <% end %>
        </h4>
        <div class="col-12 py-5 text-center">
          <h2><%= link_to "SHOP情報編集はこちら",  edit_shop_path,class: "btn btn-outline-success p-3" %></h2>
        </div>
      </div>
    <% else %>
      <div class="col-11 pb-4 user-img-center">
        <%= link_to image_tag(@user.photo_url, class: "img-fluid rounded-circle icon-trim-user-show d-block mx-auto"), user_path(@user) %>
      </div>
      <div class="col-12">
        <h4 class="mb-2 text-dark">
          名前 : <%= @user.name %>
        </h4>
        <h4 class="mb-2 text-dark">
          年齢 : 
          <% unless @user.age.blank? %>
            <%= @user.age %>歳
          <% end %>
        </h4>
        <h4 class="mb-2 text-dark">
          地域 : 
          <% unless @user.area.blank? %>
           <%= @user.area.prefecture %>
          <% end %>
        </h4>
        <h4 class="mb-2 text-dark">
          性別 : 
          <% unless @user.gender.blank? %>
            <%= @user.gender %>
          <% end %>
        </h4>
        <h4 class="mb-2 text-dark">
          身長 : 
          <% unless @user.height.blank? %>
            <%= @user.height %>cm
          <% end %>
        </h4>
        <h4 class="mb-2 text-dark">
          fecebook : 
          <% unless @user.facebook_url.blank? %>
            <%= link_to @user.facebook_url, class: "text-primary" do %><i class="fab fa-facebook-square"></i> <-click<% end %>
          <% end %>
        </h4>
        <h4 class="mb-2 text-dark">
          twitta : 
          <% unless @user.twitta_url.blank? %>
            <%= link_to @user.twitta_url, class: "text-info" do %><i class="fab fa-twitter-square"></i> <-click<% end %>
          <% end %>
        </h4>
        <h4 class="mb-2 text-dark">
          instaguram : 
          <% unless @user.instaguram_url.blank? %>
            <%= link_to @user.instaguram_url, class: "text-warning" do %><i class="fab fa-instagram"></i> <-click<% end %>
          <% end %>
        </h4>
        <div class="col-12 py-5 text-center">
          <h2><%= link_to "USER情報編集はこちら", edit_user_registration_path,class: "btn btn-outline-success p-3" %></h2>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/users/_user_show.html.erb
<!-- コンテンツ -->
<div class="container mb-5">
  <!-- user情報 -->
  <div class="row">
    <div class="col-12 row user-img-center">
      <div class="col-4">
        <%= link_to image_tag(@user.photo_url, class: "img-fluid rounded-circle icon-trim-user-show d-block mx-auto"), user_path(@user) %>
      </div>
      <div class="col-8 row">
        <div class="col-12 row py-3 ">
          <div class="col-12 pb-2 col-md-6">
            <h4>
              <%= @user.name %>
              <% unless @user.age.blank? %>
                (<%= @user.age %>歳)
              <% end %>
            </h4>
            <% unless @user.area.blank? %>
              <h6 class="mb-1 text-dark">地域 : <%= @user.area.prefecture %></h6>
            <% end %>
            <% unless @user.gender.blank? %>
              <%= @user.gender %> / 
            <% end %>
            <% unless @user.height.blank? %>
              <%= @user.height %>cm 
            <% end %>
          </div>
          <div class="col-12 col-md-6">
            <% if user_signed_in? && @user.id == current_user.id %>
              <div class="my-4">
                <%= link_to setting_users_path, class: "btn btn-warning" do %>
                  <i class="fas fa-user-cog">プロフ設定</i>
                <% end %>
              </div>
            <% end %>
            
            <!-- フォロー -->
            <% if user_signed_in? %>
              <% if current_user.id != @user.id %>
                    <% if @user.followed_by?(current_user) %>
                      <%= link_to user_relationships_path(@user.id), class: "btn btn-info" , method: :delete do %>
                        <i class="fas fa-user-tag">フォロー中</i>
                      <% end %>
                    <% else %>
                      <%= link_to user_relationships_path(@user.id), class: "btn btn-info",  method: :post do %>
                        <i class="fas fa-user-tag">フォローする</i>
                      <% end %>
                    <% end %>
                <% end %>
            <% else %>
              <div class="m-1 h-25">
                <a class="aria-expanded" data-toggle="modal" data-target="#menuModal" href="#">
                  <i class="fas fa-user-tag">フォローする</i>
                </a>
              </div>
            <% end %>
            <!-- スタッフ -->
            <div class="mt-2">
              <% if user_signed_in? %>
                <% unless current_user.shop.blank? %>
                  <% if current_user != @user %>
                    <% if @user.staffed_by?(current_user) %>
                      <%= link_to user_staffs_path(@user.id), class: "btn btn-success", method: :delete do %>
                        <h6><i class="fas fa-id-card"></i><%= current_user.name %> スタッフ</h6>
                      <% end %>
                    <% else %>
                      <%= link_to user_staffs_path(@user.id), class: "btn btn-outline-success", method: :post do %>
                        <h6><i class="fas fa-id-card"></i>スタッフ登録</h6>
                      <% end %>
                    <% end %>
                  <% end %>
                <% end %>
              <% end %>
            </div>
            <div class="mt-4">
              <h3>
                <% unless @user.facebook_url.blank? %>
                  <%= link_to @user.facebook_url, class: "mr-4  text-primary" do %><i class="fab fa-facebook-square"></i><% end %>
                <% end %>
                <% unless @user.twitta_url.blank? %>
                  <%= link_to @user.twitta_url, class: "mr-4 text-info" do %><i class="fab fa-twitter-square"></i><% end %>
                <% end %>
                <% unless @user.instaguram_url.blank? %>
                  <%= link_to @user.instaguram_url, class: "text-warning" do %><i class="fab fa-instagram"></i><% end %>
                <% end %>
              </h3>
            </div> 
          </div>
        </div>
      </div>
      <div class="col-12 row">
        <div class="col-0 col-md-4"></div><!-- 空 -->
        <div class="col-12 col-md-8">
          <div class="row">
            <p class="col-4">投稿数<strong><%= @user.posts.count %></strong>件</p>
            <a class="col-4" data-toggle="modal" data-target="#followersModal" href="#">
              <p>フォロワー<strong><%= @user.followers.count %></strong>人</p>
            </a>
            <a class="col-4" data-toggle="modal" data-target="#followingsModal" href="#">
              <p>フォロー中<strong><%= @user.followings.count %></strong>人</p>
            </a>
          </div> 
        </div>
      </div>
    </div>
  </div>
</div>


<div class="container-fluid">
  <div class="mb-4">
    <nav class="border-bottom mb-4">
      <div class="nav nav-tabs border-bottom-0 shop-show-tab justify-content-center" id="tab-menus" role="tablist">
        <a class="page-1 nav-item nav-link active" id="tab-corde" data-toggle="tab" href="#panel-corde" role="tab" aria-controls="panel-corde" aria-selected="true">過去の投稿</a>
        <a class="page-2 nav-item nav-link" id="tab-like" data-toggle="tab" href="#panel-like" role="tab" aria-controls="panel-like" aria-selected="false">イイねしてる投稿</a>
      </div>
    </nav>

    <div class="tab-content" id="panel-menus">
      <!-- 投稿 -->
      <div class="tab-pane fade show active" id="panel-corde" role="tabpanel" aria-labelledby="tab-corde">
        <div class="page-list jscroll">
          <div class="card-body row">
            <% unless @posts.blank? %>
              <% @posts.each do |post| %>
                <div class="col-4 search-img">
                  <div class="image-trim-square">
                    <%= link_to post_path(post) do %>
                      <%= image_tag(post.image.to_s, class: "img-fluid" ) %>
                      <div class="mask">
                        <div class="caption">
                          <p class="mobil-font"><i class="far fa-heart"></i> : <%= post.likes.count %></p>
                          <p class="mobil-font"><i class="fas fa-eye"></i> : <%=  post.impressionist_count %></p>
                        </div>
                      </div>
                    <% end %>
                  </div>
                </div>
              <% end %>
            <% else %>
              <div class="col-12">
                <h3 class="text-center blank-comment-py">投稿がありません。</h3>
              </div>
            <% end %> 
          </div>
          <%= paginate @posts, :param_name => 'user_post_page' %>
        </div>
      </div>
      <!-- like -->
      <div class="tab-pane fade" id="panel-like" role="tabpanel" aria-labelledby="tab-like">
        <div class="page-list-2 jscroll-2" >
          <div class="card-body row">
            <% unless @user.liked_posts.blank? %>
              <% @user.liked_posts.each do |post| %>
                <div class="col-4 search-img">
                  <div class="image-trim-square">
                    <%= link_to post_path(post) do %>
                      <%= image_tag(post.image.to_s, class: "img-fluid" ) %>
                      <div class="mask">
                        <div class="caption">
                          <p class="mobil-font"><i class="far fa-heart"></i> : <%= post.likes.count %></p>
                          <p class="mobil-font"><i class="fas fa-eye"></i> : <%=  post.impressionist_count %></p>
                        </div>
                      </div>
                    <% end %>
                  </div>
                </div>
              <% end %>
            <% else %>
              <div class="col-12">
                <h3 class="text-center blank-comment-py">投稿がありません。</h3>
              </div>
            <% end %> 
          </div>
          <%= paginate @likes, :param_name => 'like_post_page' %>
        </div>
      </div>
    </div>
  </div>
</div>

<!-- followers modal -->
<div class="modal fade" id="followersModal" tabindex="-1" role="dialog" aria-labelledby="followersModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content pb-5"> 
      <div class="modal-header">
        <h5 class="modal-title" id="followersModalLabel">FOLLOWER</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="close">
            <span aria-hide="true">✖︎</span>
          </button>
      </div>
      <div class="scroll-content overflow-auto" style="height: 400px;">
        <% unless @followers.blank? %>
          <% @followers.each do |user| %>
            <div class="my-3 ml-1 row">
              <div class="col-8">
                <%= link_to user_path(user.id) do %>
                    <%= image_tag (user.photo_url), class: "img-fluid rounded-circle s-icon" %>
                    <span class="small text-truncate"><%= user.name %></span>
                <% end %>
              </div>
              <div class="col-4">
                <% if user_signed_in? %>
                  <% if current_user.id != user.id %>
                        <% if user.followed_by?(current_user) %>
                          <%= link_to user_relationships_path(user.id), class: "btn btn-info" , method: :delete do %>
                            <i class="fas fa-user-tag small">フォロー中</i>
                          <% end %>
                        <% else %>
                          <%= link_to user_relationships_path(user.id), class: "btn btn-info",  method: :post do %>
                            <i class="fas fa-user-tag small">フォローする</i>
                          <% end %>
                        <% end %>
                    <% end %>
                <% else %>
                  <div class="btn btn-info">
                    <a class="aria-expanded" data-toggle="modal" data-target="#menuModal" href="#" class="close" data-dismiss="modal" aria-label="close">
                      <i class="fas fa-user-tag small">フォローする</i>
                    </a>
                  </div>
                <% end %>
              </div>
            </div>
          <% end %>
        <% else %>
          <div>
            <h3 class="text-center blank-comment-py">FOLLOWERは未登録です。</h3>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

<!-- followings modal -->
<div class="modal fade" id="followingsModal" tabindex="-1" role="dialog" aria-labelledby="followingsModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content pb-5"> 
      <div class="modal-header">
        <h5 class="modal-title" id="followingsModalLabel">FOLLOWER</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="close">
            <span aria-hide="true">✖︎</span>
          </button>
      </div>
      <div class="scroll-content overflow-auto" style="height: 400px;">
        <% unless @followings.blank? %>
          <% @followings.each do |user| %>
            <div class="my-3 ml-1 row">
              <div class="col-8">
                <%= link_to user_path(user.id) do %>
                    <%= image_tag (user.photo_url), class: "img-fluid rounded-circle s-icon" %>
                    <span class="small text-truncate"><%= user.name %></span>
                <% end %>
              </div>
              <div class="col-4">
                <% if user_signed_in? %>
                  <% if current_user.id != user.id %>
                        <% if user.followed_by?(current_user) %>
                          <%= link_to user_relationships_path(user.id), class: "btn btn-info" , method: :delete do %>
                            <i class="fas fa-user-tag small">フォロー中</i>
                          <% end %>
                        <% else %>
                          <%= link_to user_relationships_path(user.id), class: "btn btn-info",  method: :post do %>
                            <i class="fas fa-user-tag small">フォローする</i>
                          <% end %>
                        <% end %>
                    <% end %>
                <% else %>
                  <div class="btn btn-info">
                    <a class="aria-expanded" data-toggle="modal" data-target="#menuModal" href="#" class="close" data-dismiss="modal" aria-label="close">
                      <i class="fas fa-user-tag small">フォローする</i>
                    </a>
                  </div>
                <% end %>
              </div>
            </div>
          <% end %>
        <% else %>
          <div>
            <h3 class="text-center blank-comment-py">FOLLOWERは未登録です。</h3>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/setting.html.erb
<div class="container">
	<div class="row">
	  <div class="col-12 col-lg-3 my-2">
		<!-- pc -->
	    <div class="nav flex-column nav-pills" id="v-pills-tab" role="tablist" aria-orientation="vertical">
	      <a class="nav-link active" id="v-pills-home-tab" data-toggle="pill" href="#v-pills-home" role="tab" aria-controls="v-pills-home" aria-selected="true">プロフィール</a>
	      <a class="nav-link" id="v-pills-post-tab" data-toggle="pill" href="#v-pills-post" role="tab" aria-controls="v-pills-post" aria-selected="false">投稿の作成,編集</a>
	      <a class="nav-link" id="v-pills-follower-tab" data-toggle="pill" href="#v-pills-logout" role="tab" aria-controls="v-pills-logout" aria-selected="false">ログアウト</a>
	    </div>
	  </div>
	  <div class="col-12 col-lg-9">
	    <div class="tab-content" id="v-pills-tabContent">
	      <div class="tab-pane fade show active" id="v-pills-home" role="tabpanel" aria-labelledby="v-pills-home-tab">
	        <%= render "user.info" %>
	      </div>
	      <div class="tab-pane fade" id="v-pills-post" role="tabpanel" aria-labelledby="v-pills-post-tab">
	        <div class="container bg-white">
	        	<div class="row">
	        		<div class="col-12 border-bottom text-center py-4 mb-2">
	        			<%= link_to new_post_path, class: "btn btn-outline-success" do %>
				          <h6><i class="fas fa-pen-nib"></i> 新規投稿</h6>
				        <% end %>
	        		</div>
	        		<% unless @posts.blank? %>
	        			<% @posts.each do |post| %>
			        		<div class='col-6 col-sm-4 col-lg-3 my-1'>
	                			<div class="card mb-3">
	                				<div class="img-fluid image-trim">
					        			<% if post.image_url.present? %>
					                      <%= link_to image_tag(post.image.to_s), post_path(post) %>
					                    <% end %>
			                    	</div>
			                    	<div class='card-body text-center row'>
			                    		<%= link_to("編集", edit_post_path(post),class: "col-12 mb-3 btn btn-warning") %>
			                    		<%= link_to("削除", post_path(post),class: "col-12 btn btn-danger", method: :delete) %>
			                    	</div>
			                	</div>
			        		</div>
			        	<% end %> 
			        <% else %>
			            <div class="col-12">
			              <h3 class="text-center blank-comment-py">投稿がありません。</h3>
			            </div>
		          <% end %> 
	        	</div>
	        </div>
	      </div>
	      
		  <!-- ログアウト -->
	      <div class="tab-pane fade" id="v-pills-logout" role="tabpanel" aria-labelledby="v-pills-logout-tab">
	        <div class="row text-center my-5 py-5 bg-white">
	        	<p class="col-12 pb-3">ログアウトしますか？</p>
	        	<h6 class="col-12">
                	<%= link_to "ログアウト", destroy_user_session_path,class: "btn btn-danger", method: :delete %>
             	</h6>
	        </div>
	     </div>
	    </div>
	  </div>
	</div>
</div>

app/views/users/show.html.erb
<%= javascript_include_tag 'page_scroll' %>
<div class="my-5">
	<!-- shopとuser切り替え -->
	<% unless @user.shop.blank? %>
	  <%= render "shop_show" %>
	<% else %>
	  <%= render "user_show" %>
	<% end %>

</div>