config/routes.rb
Rails.application.routes.draw do
  # get 'contacts/new'
  # get 'contacts/create'
  get 'home/about'
  #get 'staffs/create'
  #get 'staffs/destroy'
  #get 'relationships/create'
  #get 'relationships/destroy'
  #get 'users/show'
  #get 'clothes/index'
  #get 'posts/index'
  #get 'posts/show'
  #get 'posts/new'
  #get 'posts/create'
  #get 'posts/edit'
  #get 'posts/search'

  root "posts#index"

  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  
  # /shop/newを習得
  devise_scope :user do
    get '/shop/new' => 'users/registrations#shop', as: :new_shop
    get '/shop/edit' => 'users/registrations#shop_edit', as: :edit_shop
  end

  resources :users, only: [:show] do
    collection do
      get :setting
    end
    resource :relationships, only: [:create, :destroy]
    resource :staffs, only: [:create, :destroy]
  end

  resources :posts do
  	collection do
  		get :search
  	end
    member do
      get :new2
    end
    resources :clothes, only: [:create, :destroy]
    resources :likes, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
  end
  
  resources :contacts, only: [:new, :create]

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/post.rb
class Post < ApplicationRecord
	# ビュー数
	is_impressionable

	belongs_to :user, optional: true
	
	has_many :likes, dependent: :destroy
	# 投稿が誰にいいねされているのか
	has_many :liked_users, through: :likes, source: :user
	
	has_many :comments, dependent: :destroy
	# コメントが存在するかを見るため
	has_many :commented_users, through: :comments, source: :user

	has_many :clothes, dependent: :destroy

	# どのpostにどのblandなどのclothe情報
	has_many :blanded_posts, through: :clothes, source: :bland
	has_many :categoryed_posts, through: :clothes, source: :category
	has_many :colored_posts, through: :clothes, source: :color
	has_many :sized_posts, through: :clothes, source: :size


	mount_uploader :image, ImageUploader
	mount_uploader :video, VideoUploader

	

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, only: [:create, :new]
  impressionist :actions => [:show]

  def index
    @posts = Post.all.order("created_at DESC").page(params[:post_page]).per(6)

    # shopのみ,userのみ
    @set_posts = Post.all
    @shop_posts = []
    @user_posts = []
    @set_posts.each do |post|
      if post.shop_id.present?
        @shop_posts << post
      else
        @user_posts << post
      end
    end
    @shop_posts_sort = @shop_posts.sort_by {|f| f.created_at}.reverse
    @shop_posts_sort = Kaminari.paginate_array(@shop_posts_sort).page(params[:page]).per(9)
    @user_posts_sort = @user_posts.sort_by {|f| f.created_at}.reverse
    @user_posts_sort = Kaminari.paginate_array(@user_posts_sort).page(params[:page]).per(9)
    
    # タイムライン表示
    @followings =[]
    if user_signed_in?
      current_user.followings.each do |following|
        following.posts.each do |post| 
          @followings << post
        end
      end
    end
    @followings_sort = @followings.sort_by {|f| f.created_at}.reverse
    # arrayエラーの場合
    @followings_sort = Kaminari.paginate_array(@followings_sort).page(params[:page]).per(3)

  end


  def show  
    
    @post = Post.find(params[:id])
    @clothes = @post.clothes.all

    # 過去の投稿
    @posts = @post.user.posts.all

    # 同じブランドの投稿
    @clothe_all = Clothe.all
    @clothe_post = @post.clothes.all
    @bland_posts = []
    @clothe_post.each do |post_clothe|
      @clothe_all.each do |clothe|
        if clothe.bland == post_clothe.bland
          @bland_posts << clothe.post
        end
      end
    end
    
    @comment = @post.comments.new
    @comments = @post.comments
    @commented_users = @post.commented_users

    impressionist(@post, "message...") # 2nd argument is optional
  end

  def new
    @post = Post.new
    
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    # user_idを持ったshopの子を持つuserなら
    unless current_user.shop.blank?
      @post.shop_id = current_user.shop.id
    end
    if @post.save
      flash[:notice] = "入力を保存しました"
      redirect_to new2_post_path(@post)
    else
      flash[:alert] = "保存できませんでした"
      redirect_back(fallback_location: root_path)
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    @post.update(update_post_params)
    if @post.save
      flash[:notice] = "入力を更新しました。"
      redirect_to new2_post_path(@post)
    else
      flash[:alert] = "更新できませんでした"
      redirect_back(fallback_location: root_path)
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    flash[:notice] = "投稿を削除しました"
    redirect_back(fallback_location: root_path)
  end

  def search
    @q = Post.ransack(params[:q])
    @post_images = @q.result(distinct: true).page(params[:page]).per(30)

    @area = Area.all
  end

  def new2
    @post = Post.find(params[:id])
    @clothe = @post.clothes.new
    @clothes = @post.clothes.all

    @categories = Category.all

  end



  private

  def post_params
    params.require(:post).permit(
      :title, :content, :image, :video, :shop_gender, :shop_height
      )
  end

  def update_post_params
    params.require(:post).permit(
      :title, :content, :image, :video, :shop_gender, :shop_height
      )
  end

end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_follower.index.html.erb
<div class="row">
	<% if user_signed_in? %>
		<% @followings.each do |post| %>
			<div class='col-12'>
				<!-- カード01 -->
				<div class='card row mb-4 bg-light'>
					<div class="col-12 py-1">
						<%= link_to user_path(post.user_id) do %>
							<%= image_tag(post.user.photo_url, :class => "img-fluid rounded-circle icon-trim") %>
							<span><%= post.user.name %></span>
						<% end %>
					</div>
					<div class="img-fluid overflow-hidden image-trim-110">
						<% if post.image_url.present? %>
							<%= link_to image_tag(post.image_url), post_path(post) %>
						<% end %>
					</div>
					<!-- カードエリアの本文 -->
					<div class="col-12 row pt-2">
						<div class="col-12 row">
							<div class="col-12 my-2 row justify-content-end">
								<p class="col-2">
									<% if post.user_id != current_user.id %>
										<% if current_user.already_liked?(post) %>
										  <%= link_to post_like_path(post, post.id),  method: :delete do %>
										  	<h3><i class="fas fa-heart notiine"></i></h3>
								          <% end %>
										<% else %>
											<%= link_to post_likes_path(post), method: :post do %>
									          <h3><i class="far fa-heart iine"></i></h3>
									        <% end %>
										<% end %>
									<% end %>
								</p>
							</div>
							<h6 class="col-12 pt-2 text-truncate">
								<strong><%= post.title %></strong>
							</h6>
							<p class="col-12 pt-2 text-muted text-truncate">
								<%= post.content %>
							</p>
							<p class="col-12 row pt-3">
								<span class="small col-6"><%= time_ago_in_words(post.created_at) %>前</span>
								<span class=" col-6 text-right"><i class="fas fa-eye"></i> : <%=  post.impressionist_count %></span>
							</p>
						</div>
					</div>
				</div>
			</div>
		<% end %>
	<% end %>
</div>

app/views/posts/edit.html.erb
<%= render "form" %>
 

app/views/posts/new.html.erb
<%= render "form" %>
 

app/views/posts/new2.html.erb
<div class="container bg-white py-4 my-4">
	<h4 class="text-center">タグ追加</h4>
	<%= form_for [@post, @clothe] do |clothe| %>
		<div class="row justify-content-center">
			<div class="field col-3 col-lg-4">
		        <%= clothe.label :カテゴリー %><br />
		        <div>
					<h4><a data-toggle="modal" data-target="#categoryModal" href="#"><button class="btn btn-outline-success page-1">選択</button></a></h4>
				</div>
				<div class="modal fade" id="categoryModal" tabindex="-1" role="dialog" aria-labelledby="categoryModalLabel" aria-hidden="true">
					<div class="modal-dialog modal-dialog-centered modal-xl" role="document">
						<div class="modal-content pb-5"> 
							<div class="modal-header sticky-top bg-light">
								<h5 class="modal-title" id="categoryModalLabel">カテゴリー</h5>
								<button type="button" class="close" data-dismiss="modal" aria-label="close">
						  			<span aria-hide="true">✖︎</span>
						  		</button>
							</div>
							<div class="modal-body mb-3 row">
						        <%= clothe.collection_radio_buttons :category_id, @categories, :id, :name do |tag| %>
						        	<div class="m-3 border-bottom">
								        <%= tag.label do %>
								            <%= tag.radio_button %>
								            <%= tag.text %>
								        <% end %>
							        </div>
			    				<% end %>	
			    			</div>
						</div>
		 			</div>
				</div>
	     	</div>
	     	<div class="field col-3 col-lg-4">
		        <%= clothe.label :サイズ %><br />
		        <%= clothe.collection_select :size_id, Size.all, :id, :name, :include_blank => true %>
	     	</div>
	     	<div class="field col-3 col-lg-4">
		        <%= clothe.label :カラー %><br />
		        <%= clothe.collection_select :color_id, Color.all, :id, :name %>
	     	</div>
     		<div class="field mt-2 col-6 col-lg-4">
		        <%= clothe.label :ブランド %><br />
		        <%= clothe.text_field :bland %>
	     	</div>
	     	<div class="field mt-2 col-6 col-lg-4">
		        <%= clothe.label :商品名 %><br />
		        <%= clothe.text_field :name %>
	     	</div>
	     	<% unless @post.user.shop.blank? %>
		     	<div class="field mt-2 col-12 col-lg-4">
			        <%= clothe.label :プライス %><span class="small">（数字のみ入力）</span><br />
			        <%= clothe.number_field :price %>
		     	</div>
		    <% end %>
	     	<div class="field pt-5 text-center col-12">
				<%= clothe.submit "+ 追加", data: { disable_with: "追加中..."}, class: "btn btn-success" %>
			</div>
		</div>
		<p class="text-center pt-3">複数のタグを追加できます。</p>
	<% end %>
</div>
<div class="container-furuid">
	<div class="card border-0 posts-bg">
		<div class="card-body">
			<!-- タグ -->
			<p class="border-bottom text-center">タグ一覧</p>
			<div class="row">
				<% unless @clothes.blank? %>
					<% @clothes.each do |clothe| %>
						<div class="col-6 col-md-4 col-lg-3 py-1 mb-2">
							<div>
								<i class="fas fa-tag bg-tag" style="color:<%= clothe.color.css_color %>;"></i>
							</div>
							<div>
								<% unless clothe.category.blank? %>
								<div class="tab-categoey row">
									<%= image_tag(clothe.category.item_url, class: "img_field col-3" ) %>
								</div>
								<% end %>
							</div>
							<% if clothe.color.name == "ホワイト系" || clothe.color.name == "イエロー系" || clothe.color.name == "ベージュ系" %>
								<div class="clothe-tab">
									<div >
										<% unless clothe.bland.blank? %>
											<h6 class="text-wrap clothes-text mb-2" style="width: 9rem;"><%= clothe.bland %></h6>
										<% end %>
									</div>
									<div>
										<% unless clothe.name.blank? %>
											<h6 class="text-wrap clothes-text mb-2" style="width: 9rem;"><%= clothe.name %></h6>
										<% end %>
									</div>
									<% unless @post.user.shop.blank? %>
										<div>
											<% unless clothe.price.blank? %>
												<h6 class="text-wrap clothes-text mb-2" style="width: 9rem;">¥<%= clothe.price %></h6>
											<% end %>
										</div>	
									<% end %>
									<div>
										<% unless clothe.size.blank? %>
											<h6 class="text-wrap clothes-text mb-2" style="width: 9rem;"><%= clothe.size.name %></h6>
										<% end %>
									</div>
								</div>
							<% else %>
								<div class="clothe-tab">
									<div >
										<% unless clothe.bland.blank? %>
											<h6 class="text-white text-wrap clothes-text mb-2" style="width: 9rem;"><%= clothe.bland %></h6>
										<% end %>
									</div>
									<div>
										<% unless clothe.name.blank? %>
											<h6 class="text-white text-wrap clothes-text mb-2" style="width: 9rem;"><%= clothe.name %></h6>
										<% end %>
									</div>
									<% unless @post.user.shop.blank? %>
										<div>
											<% unless clothe.price.blank? %>
												<h6 class="text-white text-wrap clothes-text mb-2" style="width: 9rem;">¥<%= clothe.price %></h6>
											<% end %>
										</div>	
									<% end %>
									<div>
										<% unless clothe.size.blank? %>
											<h6 class="text-white text-wrap clothes-text mb-2" style="width: 9rem;"><%= clothe.size.name %></h6>
										<% end %>
									</div>
								</div>
							<% end %>
							<div class="tag-delete">
								<% unless clothe.id.blank? %><!-- 空のバグを弾く -->
									<%= link_to("削除", post_clothe_path(clothe.post_id, clothe.id),class: "ml-5 btn btn-outline-danger", method: :delete) %>
								<% end %>
							</div>
						</div>
					<% end %>
				<% else %>
				<div class="col-12">
					<p class="py-5 text-center">タグ未登録</h6>
				</div>
				<% end %>
			</div>
		</div>
	</div>
</div>
<div class="container py-4 bg-white rounded">
	<h4 class="text-center pb-5">投稿プレビュー</h4>
	<div class="row justify-content-center">
		<div class="col-12 col-lg-5">
			<div id="img_field" class="d-block mx-auto mb-3">
				<%= image_tag(@post.image.to_s) %>
			</div>
		</div>
		<div class="col-12 col-lg-7">
			<h5 class="">コーディネートタイトル</h5>
			<div class="text-break py-3 border bg-light rounded">
				<%= @post.title %>
			</div>
			<h5 class="pt-5">コーディネート詳細</h5>
			<div class="text-break py-3 border bg-light rounded">
				<%= @post.content %>
			</div>
			<h5 class="pt-5">モデル情報</h5>
			<div class="text-break py-3 border bg-light text-center rounded">
				<% unless @post.user.shop.blank? %>
			        <% unless @post.shop_gender.blank? %>
			          <%= @post.shop_gender %> / 
			        <% end %>
			        <% unless @post.shop_height.blank? %>
			          <%= @post.shop_height %>cm
			        <% end %>
			    <% end %>
			</div>	
		</div>
		<div class="col-12 my-3">
			<% unless @post.video.blank? %>
				<%= video_tag @post.video.url, width: "100%", controls: true, autobuffer: true %>
			<% end %>
		</div>	
	</div>
	<div class="row justify-content-center mt-3" >
		<%= link_to("編集", edit_post_path(@post),class: "col-5 btn btn-outline-danger") %>
	</div>	
</div>
<div class="container-furuid my-1 py-5 bg-light">
	<p class="text-center">この内容で投稿？</p>
	<div class="container my-2 py-4 bg-white">
		<div class="row justify-content-center">
			<%= link_to "投稿する", post_path(@post), class: "btn btn-success col-4" %>
		</div>	
	</div>
</div>

app/views/posts/show.html.erb
<!-- ogp上書き -->
<% set_meta_tags title: @post.title , description: @post.content.to_s.gsub(/\r\n|\r|\n|\s|\t/, ""), og:{image: image_url(url_for(@post.image.to_s))}, twitter:{image: image_url(url_for(@post.image.to_s))} %>
<!-- コンテンツ -->
<div class="container my-5">
	<div class="row justify-content-center">
		<!-- カード1 -->
		<div class="col-md-12 col-lg-11 mb-2">
			<div class="card">
				<div class="row no-gutters">
					<div class="col-12 col-sm-6">
						<div class="image-trim">
							<% unless @clothes.blank? %>
								<a data-toggle="modal" data-target="#tagsModal" href="#">
									<%= image_tag(@post.image.to_s, class: "card-img") %>
									<i class="fas fa-tag tag-image"></i>
								</a>
							<% else %>
								<a data-toggle="modal" data-target="#tagsModal" href="#">
									<%= image_tag(@post.image.to_s, class: "card-img") %>
								</a>
							<% end %>
						</div>
						<div class="row pt-3">
							<div class="col-6 text-center">
								<div id="likes_buttons_<%= @post.id %>">
						            <%= render partial: 'likes/showlike', locals: { post: @post} %>
						        </div>
							</div>
							<div class="col-6 text-center">
								<h4><i class="fas fa-eye"></i> : <%=  @post.impressionist_count %></h4>
							</div>
						</div>
					</div>
					<div class="col-12 col-sm-6">
						<div class="card-body">
							<div class="border-bottom py-2 row">
								<div class="col-6">
									<!-- user -->
									<%= link_to user_path(@post.user_id) do %>
										<%= image_tag(@post.user.photo_url, :class => "img-fluid rounded-circle s-icon") %>
										<span><%= @post.user.name %></span>
									<% end %>
								</div>
								<!-- フォロー -->
								<div class="col-6">	
									<% if user_signed_in? %>
										<% if current_user.id != @post.user_id %>
									        <% if @post.user.followed_by?(current_user) %>
									        	<%= link_to user_relationships_path(@post.user), method: :delete do %>
										          <i class="fas fa-user-tag">フォロー中</i>
										        <% end %>
									        <% else %>
									        	<%= link_to user_relationships_path(@post.user), method: :post do %>
										          <i class="fas fa-user-tag">フォローする</i>
										        <% end %>
									        <% end %>
									    <% end %>
									<% else %>
										<div class="m-1 h-25 float-left">
											<a class="aria-expanded" data-toggle="modal" data-target="#menuModal" href="#">
												<i class="fas fa-user-tag">フォローする</i>
											</a>
										</div>
								    <% end %>
								</div>
							</div>
							<div class="col-12 row scroll-content overflow-auto" >
								<div class="col-12 my-4 row">
									<h6 class="col-12 bg-light">
										<strong><%= @post.title %></strong>
										<p class="py-2"><%= @post.content %></p>
										<p class="small"><%= time_ago_in_words(@post.created_at) %>前</p>
									</h6>
								</div>
								<!-- コメント内容 -->
								<% unless @commented_users.blank? %>
							        <% @comments.each do |comment| %>
										<div class="col-12 row mb-4">
								        	<% unless comment.user_id.blank? %><!-- 空のバグを弾く -->
											    <% if user_signed_in? && comment.user.id == current_user.id %>
											    	<div class="col-12 text-right mycomment-messege-border">
											    		<p class="small"><%= comment.content %></p>
											    		<div class="row">
											    			<!-- コメントの投稿主の削除権限 -->
												    		<% if comment.user_id == current_user.id %>
														    	<%= link_to("削除", post_comment_path(comment.post_id, comment.id),class: "col-4 small text-danger", method: :delete) %>
														    <!-- 投稿主の削除権限 -->
														    <% elsif @post.user.id == current_user.id %>
														    	<%= link_to("削除", post_comment_path(comment.post_id, comment.id),class: "col-4 small text-danger", method: :delete) %>
														    <% end %>
											    			<span class="col-8 small"><%= time_ago_in_words(comment.created_at) %>前</span>
														</div>
											    	</div>
											    <% else %>
											    	<div class="col-12">	
												    	<% unless comment.user.blank? %>
										            		<%= link_to user_path(comment.user_id) do %>
																<%= image_tag(comment.user.photo_url, :class => "img-fluid rounded-circle s-icon") %>
																<span><%= comment.user.name unless comment.user.blank? %></span>
															<% end %>
										            	<% end %>
										            </div>
											    	<div class="col-12 comment-messege-border">
											    		<p class="small"><%= comment.content %></p>
											    		<div class="row">
											    			<span class="col-8 small"><%= time_ago_in_words(comment.created_at) %>前</span>
											    			<!-- 投稿主の削除権限 -->
														    <% if user_signed_in? && @post.user.id == current_user.id %>
														    	<%= link_to("削除", post_comment_path(comment.post_id, comment.id),class: "col-4 small text-danger", method: :delete) %>
														    <% end %>
														</div>
											    	</div>
											    <% end %>
											<% end %>
										</div>
									<% end %>
								<% else %>
									<h6 class="text-center">コメントの投稿がありません</h6>
								<% end %>
							</div>
							<!-- コメント入力 -->
							<div>
								<% if user_signed_in? %>
								    <%= form_for [@post, @comment] do |f| %>
									    <div class="border-top py-1 row justify-content-center">
										  <%= f.text_field :content, placeholder: 'コメントを入力..', class: "col-8 py-1", "presence"=> true %>
										  <%= f.submit "投稿", class: "btn btn-info col-3 ml-1" %>
										</div>
									<% end %>
								<% end %>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>

		<div class="col-12 my-4">
			<% unless @post.video.blank? %>
				<%= video_tag @post.video.url, width: "100%", controls: true, autobuffer: true %>
			<% end %>
		</div>
		<div class="col-12">
			<div>
				<div>
					<h5><p class="border-bottom text-center py-3"><%= @post.user.name %>の他の投稿</p></h5>
				</div>
				<div class="row mb-4">
					<% unless @posts.blank? %>
						<% @posts.shuffle.first(3).each do |post| %>
							<div class="col-4 search-img">
								<div class="image-trim-square">
									<% if post.image.to_s.present? %>
				                      <%= link_to  post_path(post) do %>
						                    <%= image_tag(post.image.to_s, class: "img-fluid") %>
						                    <div class="mask">
												<div class="caption">
													<p class="mobil-font"><i class="far fa-heart"></i> : <%= post.likes.count %></p>
													<p class="mobil-font"><i class="fas fa-eye"></i> : <%=  post.impressionist_count %></p>
												</div>
											</div>
				                      <% end %>
				                    <% end %>
				                </div>
							</div>
						<% end %>
					<% else %>
						<h6 class="col-12 text-center py-5">過去の投稿がありません。</h6>
					<% end %>
				</div>

				<div class=" card-body">
					<h5><p class="border-bottom text-center py-3">同じブランド着用投稿</p></h5>
				</div>
				<div class="row mb-4">
					<% unless @bland_posts.blank? %>
						<% @bland_posts.shuffle.first(3).each do |post| %>
							<div class="col-4 search-img">
								<div class="image-trim-square">
									<% if post.image.to_s.present? %>
				                      <%= link_to  post_path(post) do %>
						                    <%= image_tag(post.image.to_s, class: "img-fluid") %>
						                    <div class="mask">
													<div class="caption">
														<p class="mobil-font"><i class="far fa-heart"></i> : <%= post.likes.count %></p>
														<p class="mobil-font"><i class="fas fa-eye"></i> : <%=  post.impressionist_count %></p>
													</div>
												</div>
				                      <% end %>
				                    <% end %>
				                </div>
							</div>
						<% end %>
					<% else %>
						<h6 class="col-12 text-center py-5">同じブランドの投稿がありません。</h6>
					<% end %>
				</div>
			</div>
		</div>
	</div>
</div>

<!-- タグ -->
<div class="modal fade" id="tagsModal" tabindex="-1" role="dialog" aria-labelledby="tagsModalLabel" aria-hidden="true">
  	<div class="modal-dialog modal-dialog-centered modal-xl" role="document">
    	<div class="modal-content pb-5" style="background-color: #EEEEEE;"> 
	      	<div class="modal-header sticky-top bg-light">
	        	<h5 class="modal-title" id="tagsModalLabel"></h5>
	        	<button type="button" class="close" data-dismiss="modal" aria-label="close">
	          		<span aria-hide="true">✖︎</span>
	        	</button>
	      	</div>
			<div class="card-body">
				<!-- shopとuserで引き出し別 -->
				<p class="border-bottom mb-5">モデル情報: 
					<% unless @post.user.shop.blank? %>
				        <% unless @post.shop_gender.blank? %>
				          <%= @post.shop_gender %> / 
				        <% end %>
				        <% unless @post.shop_height.blank? %>
				          <%= @post.shop_height %>cm
				        <% end %>
					<% else %>
						<% unless @post.user.gender.blank? %>
				          <%= @post.user.gender %> / 
				        <% end %>
				        <% unless @post.user.height.blank? %>
				          <%= @post.user.height %>cm 
				        <% end %>
				    <% end %>
				</p>
				<!-- アイテム -->
				<p class="border-bottom">タグ</p>
				<div class="row">
					<% @clothes.each do |clothe| %>
						<div class="col-6 col-md-4 col-lg-3 py-1 mb-2">
							<div>
								<i class="fas fa-tag bg-tag" style="color:<%= clothe.color.css_color %>;"></i>
							</div>
							<div>
								<% unless clothe.category.blank? %>
								<div class="tab-categoey row">
									<div class="col-3">
										<%= image_tag(clothe.category.item_url, class: "img-fluid" ) %>
									</div>	
								</div>
								<% end %>
							</div>
							<% if clothe.color.name == "ホワイト系" || clothe.color.name == "イエロー系" || clothe.color.name == "ベージュ系" %>
								<div class="clothe-tab">
									<div >
										<% unless clothe.bland.blank? %>
											<h6 class="text-wrap clothes-text mb-2" style="width: 9rem;"><%= clothe.bland %></h6>
										<% end %>
									</div>
									<div>
										<% unless clothe.name.blank? %>
											<h6 class="text-wrap clothes-text mb-2" style="width: 9rem;"><%= clothe.name %></h6>
										<% end %>
									</div>
									<% unless @post.user.shop.blank? %>
										<div>
											<% unless clothe.price.blank? %>
												<h6 class="text-wrap clothes-text mb-2" style="width: 9rem;">¥<%= clothe.price %></h6>
											<% end %>
										</div>	
									<% end %>
									<div>
										<% unless clothe.size.blank? %>
											<h6 class="text-wrap clothes-text mb-2" style="width: 9rem;"><%= clothe.size.name %></h6>
										<% end %>
									</div>
								</div>
							<% else %>
								<div class="clothe-tab">
									<div >
										<% unless clothe.bland.blank? %>
											<h6 class="text-white text-wrap clothes-text mb-2" style="width: 9rem;"><%= clothe.bland %></h6>
										<% end %>
									</div>
									<div>
										<% unless clothe.name.blank? %>
											<h6 class="text-white text-wrap clothes-text mb-2" style="width: 9rem;"><%= clothe.name %></h6>
										<% end %>
									</div>
									<% unless @post.user.shop.blank? %>
										<div>
											<% unless clothe.price.blank? %>
												<h6 class="text-white text-wrap clothes-text mb-2" style="width: 9rem;">¥<%= clothe.price %></h6>
											<% end %>
										</div>	
									<% end %>
									<div>
										<% unless clothe.size.blank? %>
											<h6 class="text-white text-wrap clothes-text mb-2" style="width: 9rem;"><%= clothe.size.name %></h6>
										<% end %>
									</div>
								</div>
							<% end %>
						</div>
					<% end %>
				</div>
			</div>
		</div>
	</div>
</div>