config/routes.rb
Rails.application.routes.draw do
  # get 'contacts/new'
  # get 'contacts/create'
  get 'home/about'
  #get 'staffs/create'
  #get 'staffs/destroy'
  #get 'relationships/create'
  #get 'relationships/destroy'
  #get 'users/show'
  #get 'clothes/index'
  #get 'posts/index'
  #get 'posts/show'
  #get 'posts/new'
  #get 'posts/create'
  #get 'posts/edit'
  #get 'posts/search'

  root "posts#index"

  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  
  # /shop/newを習得
  devise_scope :user do
    get '/shop/new' => 'users/registrations#shop', as: :new_shop
    get '/shop/edit' => 'users/registrations#shop_edit', as: :edit_shop
  end

  resources :users, only: [:show] do
    collection do
      get :setting
    end
    resource :relationships, only: [:create, :destroy]
    resource :staffs, only: [:create, :destroy]
  end

  resources :posts do
  	collection do
  		get :search
  	end
    member do
      get :new2
    end
    resources :clothes, only: [:create, :destroy]
    resources :likes, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
  end
  
  resources :contacts, only: [:new, :create]

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/area.rb
class Area < ApplicationRecord
	has_many :users
end

app/models/category.rb
class Category < ApplicationRecord

	mount_uploader :item, ItemUploader
end

app/models/clothe.rb
class Clothe < ApplicationRecord
	belongs_to :category, optional: true
	belongs_to :color, optional: true
	belongs_to :size, optional: true

	belongs_to :post, optional: true
	
	

end

app/models/color.rb
class Color < ApplicationRecord
	has_many :clothes, dependent: :destroy
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :post, optional: true
	belongs_to :user, optional: true

	validates :content, presence: true
end

app/models/contact.rb
class Contact < ApplicationRecord
	validates :email, presence: true, length: {maximum:255},
                    format: {with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i}
	validates :message, presence: true
	validates :name, presence: true
end

app/models/like.rb
class Like < ApplicationRecord
	belongs_to :user
	belongs_to :post
	
end

app/models/post.rb
class Post < ApplicationRecord
	# ビュー数
	is_impressionable

	belongs_to :user, optional: true
	
	has_many :likes, dependent: :destroy
	# 投稿が誰にいいねされているのか
	has_many :liked_users, through: :likes, source: :user
	
	has_many :comments, dependent: :destroy
	# コメントが存在するかを見るため
	has_many :commented_users, through: :comments, source: :user

	has_many :clothes, dependent: :destroy

	# どのpostにどのblandなどのclothe情報
	has_many :blanded_posts, through: :clothes, source: :bland
	has_many :categoryed_posts, through: :clothes, source: :category
	has_many :colored_posts, through: :clothes, source: :color
	has_many :sized_posts, through: :clothes, source: :size


	mount_uploader :image, ImageUploader
	mount_uploader :video, VideoUploader

	

end

app/models/relationship.rb
class Relationship < ApplicationRecord
	belongs_to :following, class_name: "User"
	belongs_to :follower, class_name: "User"
	 #バリデーション
    validates :follower_id, presence: true
    validates :following_id, presence: true
end

app/models/scraping.rb
class Scraping < ApplicationRecord
	require "mechanize"

	def self.scrape
		
	end

end

app/models/shop.rb
class Shop < ApplicationRecord
	belongs_to :user, inverse_of: :shop
	
end

app/models/size.rb
class Size < ApplicationRecord
	has_many :clothes, dependent: :destroy
end

app/models/staff.rb
class Staff < ApplicationRecord
	belongs_to :registering, class_name: "User"
	belongs_to :registered, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  	devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable#, :confirmable

    # ビュー数
    is_impressionable

    has_many :posts, dependent: :destroy
    has_many :likes, dependent: :destroy
    # userがどの投稿をいいねしているのか
  	has_many :liked_posts, through: :likes, source: :post
  	
    has_many :active_relationships, class_name: "Relationship", foreign_key: :following_id
    has_many :followings, through: :active_relationships, source: :follower
    has_many :passive_relationships, class_name: "Relationship", foreign_key: :follower_id
    has_many :followers, through: :passive_relationships, source: :following

    has_many :active_staffs, class_name: "Staff", foreign_key: :registering_id
    has_many :registerings, through: :active_staffs, source: :registered
    has_many :passive_staffs, class_name: "Staff", foreign_key: :registered_id
    has_many :registereds, through: :passive_staffs, source: :registering

  	has_many :comments, dependent: :destroy
  	belongs_to :area, optional: true

    has_one :shop, inverse_of: :user, dependent: :destroy
    #shopのフォームでuserを保存
    accepts_nested_attributes_for :shop, allow_destroy: true
    

    mount_uploader :photo, PhotoUploader



    # follow済み？
    def followed_by?(user)
       passive_relationships.find_by(following_id: user.id).present?
    end

    # staff登録済み？
    def staffed_by?(user)
       passive_staffs.find_by(registering_id: user.id).present?
    end

    #  like済み？
    def already_liked?(post)
      self.likes.exists?(post_id: post.id)
    end

end

app/helpers/clothes_helper.rb
module ClothesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/staffs_helper.rb
module StaffsHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def bootstrap_devise_error_messages!
    return "" if resource.errors.empty?

    html = ""
    resource.errors.full_messages.each do |error_message|
      html += <<-EOF
      <div class="alert alert-danger alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert">
          <span aria-hidden="true">&times;</span>
          <span class="sr-only">close</span>
        </button>
        #{error_message}
      </div>
      EOF
    end
    html.html_safe
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Westyle</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= favicon_link_tag('favicon.ico') %>
    <!-- ogp -->
    <%= display_meta_tags(default_meta_tags) %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!-- bootstrap -->
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <!-- css -->
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <!-- fontawesome -->
    <link href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.9.0/css/all.min.css" integrity="sha256-UzFD2WYH2U1dQpKDjjZK72VtPeWP50NoJjd26rnAdUI=" crossorigin="anonymous" />
    <!-- js -->
    <%= javascript_include_tag 'jquery.jscroll.min' %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    
  </head>

  <body>

    <!-- pcヘッダー -->
    <header class='sticky-top mb-3 d-none d-md-block'>
      <div class="container">
        <div class="row">
          <!-- ロゴ -->
          <div class='col-2 logo_img'>
            <%= link_to image_tag('/assets/logo.png', class: "img-fluid mt-2 logo-size"), posts_path %>
          </div>
          <div class="col-10 row justify-content-end">
            <!-- ホーム -->
            <div class='col-1 mt-3'>
              <h5>
                <%= link_to posts_path, class: "text-dark" do %>
                  <i class="fas fa-home"></i>
                <% end %>
              </h5>
            </div>
            <!-- サーチ -->
            <div class='col-1 mt-3'>
              <h5>
                <%= link_to search_posts_path, class: "text-dark" do %>
                  <i class="fas fa-search"></i>
                <% end %>
              </h5>
            </div>
            <!-- 新規投稿 -->
            <div class='col-1 mt-3'>
              <h5>
                <%= link_to new_post_path, class: "text-dark" do %>
                  <i class="fas fa-pen-nib"></i>
                <% end %>
              </h5>
            </div>
            <!--user -->
            <div class="col-2 mt-2">
              <%if user_signed_in? %>
                <%= link_to user_path(current_user) do %>
                  <%= image_tag current_user.photo_url, class: "img-fluid rounded-circle s-icon" %>
                <% end %>
              <%else%>
                <h6 class="pt-2">
                  <a class="aria-expanded text-dark" data-toggle="modal" data-target="#menuModal" href="#">
                    <i class="fas fa-user"></i>
                  </a>
                </h6>
              <% end %>
            </div>
          </div>
        </div>
      </div>
      <!-- メッセージ -->
      <div class="container messege-abusolute">
        <div class="row ml-5 time-limit">
          <% if notice %>
            <div class="text-center messege-border">
              <p class="py-3"><strong><%= notice %></strong></p>
            </div>
          <% end %>
          <% if alert %>
            <div class="text-center alart-messege-border">
              <p class="py-3"><strong><%= alert %></strong></p>
            </div>
          <% end %>
        </div>
      </div> 
    </header>

    <!-- スマホのヘッダー -->
    <div class='d-md-none mobil-header'>
      <div class="container-fluid">
        <div class="row">
          <div class='col-12'>
            <%= link_to image_tag('/assets/logo.png', class: "img-fluid mt-3 logo-size"), posts_path %>
          </div>
        </div>
      </div>
      <!-- メッセージ -->
      <div class="sticky-top">
        <div class="row time-limit mobil-messege-abusolute">
          <% if notice %>
            <div class="text-center messege-border">
              <p class="py-3"><strong><%= notice %></strong></p>
            </div>
          <% end %>
          <% if alert %>
            <div class="text-center alart-messege-border">
              <p class="py-3"><strong><%= alert %></strong></p>
            </div>
          <% end %>
        </div>
      </div>
    </div> 

    
    <!-- 新規登録モーダル -->
    <div class="modal fade" id="menuModal" tabindex="-1" role="dialog" aria-labelledby="menuModalLabel" aria-hidden="true">
      <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content pb-5"> 
          <div class="modal-header">
            <h1 class="modal-title" id="menuModalLabel">MENU</h1>
            <button type="button" class="close" data-dismiss="modal" aria-label="close">
              <span aria-hide="true">✖︎</span>
            </button>
          </div>
          <div class="mb-3 text-center border-bottom pb-5">
            <h5 class="border-bottom py-5">
              <%= link_to "ログイン", new_user_session_path, class: "btn btn-secondary" %>
            </h5>
            <h5 class="py-5"><%= link_to "USER新規登録", new_user_registration_path, class: "btn btn-secondary" %></h5>
            <h5><%= link_to "SHOP新規登録", new_shop_path, class: "btn btn-secondary" %></h5>
          </div>
        </div>
      </div>
    </div>


    <%= yield %>


    <!-- pcフッター -->
    <footer>
      <div class="row justify-content-center">
        <div class="col-8 row text-center my-5">
          <%= link_to "初めての方", home_about_path, class: "col-6" %>
          <%= link_to "問い合わせ", new_contact_path, class: "col-6" %>
        </div>
      </div>
      <p class="text-center text-white py-5"><small>Copyright &copy;2020 WE STYLE,All Rights Reserved.</small></p>
    </footer>

    <!-- モバイルフッター -->
    <div class="footer-menu fixed-bottom d-md-none">
      <div class="container-fluid">
        <div class="row text-center justify-content-center">
          <!-- ホーム -->
          <div class="col-3">
            <h5>
              <%= link_to posts_path, class: "text-dark btn" do %>
                <i class="fas fa-home"></i>
                <p>ホーム</p>
              <% end %>
            </h5>
          </div>
          <!-- サーチ -->
          <div class="col-3">
              <%= link_to search_posts_path, class: "text-dark btn" do %>
               <i class="fas fa-search"></i>
               <p>サーチ</p>
              <% end %>
          </div>
          <div class="col-3">
            <%= link_to new_post_path, class: "text-dark btn" do %>
              <i class="fas fa-pen-nib"></i>
              <p>投稿</p>
            <% end %>
          </div>
          <!-- user -->
          <div class="col-3">
            <%if user_signed_in? %>
              <%= link_to user_path(current_user), class: "text-dark btn" do %>
                <%= image_tag current_user.photo_url, class: "img-fluid rounded-circle s-icon" %>
              <% end %>
            <% else %>
              <h6>
                <a class="aria-expanded text-dark btn" data-toggle="modal" data-target="#menuModal" href="#">
                  <i class="fas fa-user"></i>
                  <p>user</p>
                </a>
              </h6>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </body>
</html>